### ISSUE TITLE
C iPerf3

### ISSUE THREAD

**Issue by pjebs** [docooler/goIperf#1]
I love your port of iperf but I have some questions

1) Why does it have much less lines of code than the original? Is it because you've removed lots of features.

2) Can this connect to the original version in server or client mode?

3) Is this a port of of iPerf3?

Great work!

**Comment by pjebs** [comment]
4) Does it use exactly the same technique to measure the internet connection speed?

5) When in server mode, can it connect to at most 1 client? If so, then what kind of error message will it provide if a second client attempts to connect?

6) Does it format the errors into json like the C version?

7) Is it possible to easily extend your version so I can have it listen on another port and continually ask if it is currently busy with a client?

**Comment by docooler** [comment]
@pjebs sorry reply you so latter.below is my answer:
This isn't a pure iPerf3 porting. I wrote this tool inspire IPerf3. But It's different with Iperf3 If you read the code. for IPerf3 if you want to send data to Iperf server the server need a public Ip address. to resolve this issue I rewrite the server side. honestly, I don't read the IPerf3 original code. Only copy some of command line options. Off course the speed is formatted as JSON. but the error info not.
